---
title: "CMDA-4654"
subtitle: "Project 1"
author: "Matthew Pinho and Daniel Schlicht"
date: "November 16, 2020"
output:
  pdf_document:
    highlight: haddock
keep_tex: no
number_sections: no
html_document:
  df_print: paged
geometry: margin = 0.5in
header-includes:
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage{threeparttablex}
- \usepackage[normalem]{ulem}
- \usepackage{makecell}
- \usepackage{xcolor}
editor_options:
  chunk_output_type: console
documentclass: article
urlcolor: blue
---

```{r setup, include=FALSE}
# This is the setup chunk
#  Here you can set global options for the entire document

library(knitr) # I recommend doing this here

# Although you can call functions from a library using the following notation
#  without loading the entire library.
knitr::opts_chunk$set(echo = TRUE, 
                      comment = NA, # Required
                      fig.path = "./figures/",  # Store all figures here in relative path (make the folder first)
                      fig.align = "center",
                      fig.width = 7,
                      fig.height = 7,
                      message = FALSE, # Turn off load messages
                      warning = FALSE # Turn off warnings
                      )

```

\clearpage

```{r include=FALSE}
# You should not echo this chunk.
# include=FALSE does more than echo=FALSE, it actually does: echo=FALSE, results='hide', message=FALSE, warning=FALSE, fig.show='hide'

# You should set your working directory at the very beginning of your R Markdown file
# setwd("~/Dropbox/teaching/FA2020/CMDA_4654/homework/homework1/")

# In linux ~/ is shorthand for /home/username/
# You should type things out properly for your system
# Mac: /Users/username/Documents/CMDA4654/Lectures/Lecture_03/.../
# Windows: C:/Users/username/Documents/etc/Lecture/Lecture_03/.../

setwd('~/School/Fall\ 2020/CMDA4654/Projects/CMDA-4654-Project1/')
library(ggplot2)
source('./myloess.R')
source('./mykNN.R')
```

# Problem 1
## Part 1
```{r}
# load data
load('data/ozone.RData')
data('ozone')

fit1 <- lm(ozone ~ poly(temperature, 1, raw=TRUE), data = ozone)
ozone$p1 <- predict(fit1)
fit2 <- lm(ozone ~ poly(temperature, 2, raw=TRUE), data = ozone)
ozone$p2 = predict(fit2)
fit3 <- lm(ozone ~ poly(temperature, 3, raw=TRUE), data = ozone)
ozone$p3 = predict(fit3)
fit4 <- lm(ozone ~ poly(temperature, 4, raw=TRUE), data = ozone)
ozone$p4 = predict(fit4)
fit5 <- lm(ozone ~ poly(temperature, 5, raw=TRUE), data = ozone)
ozone$p5 = predict(fit5)
fit6 <- lm(ozone ~ poly(temperature, 6, raw=TRUE), data = ozone)
ozone$p6 = predict(fit6)

ggplot(ozone, aes(x = temperature, y = ozone)) + theme_bw() +
  geom_point() + 
  geom_line(aes(y=p1), size = 0.5, color = 'blue') +
  geom_line(aes(y=p2), size = 0.5, color = 'red') +
  geom_line(aes(y=p3), size = 0.5, color = 'green') +
  geom_line(aes(y=p4), size = 0.5, color = 'cyan') +
  geom_line(aes(y=p5), size = 0.5, color = 'violet') +
  geom_line(aes(y=p6), size = 0.5, color = 'black') +
  ggtitle('Polynomial Regressions of Degrees 1 to 6')
```
Answer here.

## Part 2
```{r, echo=FALSE}
# Create a table to store data
loess_table <- matrix(ncol = 3)

# create vector to store plots
my_plots <- vector()

# loop through span and degree
for(d in 1:2){
  for(s in seq(0.25, 0.75, 0.05)) {
    fit <- myloess(ozone$temperature, ozone$ozone, s, d, show.plot = FALSE)
    loess_table <- rbind(loess_table, c(fit[["span"]], fit[["degree"]], fit[["SSE"]]))
    plots <- cbind(my_plots, fit$loessplot)
  }
}
loess_table <- loess_table[-1,]
loess_table <- as.table(loess_table)
colnames(loess_table) <- c('span', 'degree', 'SSE')
rownames(loess_table) <- c()
knitr::kable(loess_table, 'pipe')
```

## Part 3
```{r}
std_plots <- vector()
for(d in 1:2){
  for(s in seq(0.25, 0.75, 0.05)) {
    fit <- loess(ozone$ozone ~ ozone$temperature, degree = d, span = s)
  }
}
```

# Problem 2
## Part 1

## Part 2


